# Generated by Django 6.1 on 2026-08-24 18:24

import apps.bureau.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0011_fix_statut_cf_wrongly_set_by_import'),
        ('referentiel', '0005_departement_code_sousprefecture_code_village_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_traitement', models.CharField(choices=[('ZIP_SHAPE', 'Traitement ZIP / Shape'), ('PDF_CF', 'Édition PDF CF'), ('PDF_DTV', 'Édition PDF DTV'), ('REPRISE_CF', 'Reprise CF'), ('REPRISE_DTV', 'Reprise DTV'), ('A0_CF', 'A0 CF')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=apps.bureau.models.upload_rapport_bureau_to)),
                ('nb_parcelles', models.IntegerField(default=0)),
                ('superficie_totale', models.FloatField(default=0)),
                ('repartition_village', models.JSONField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_bureau', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_bureau', to='referentiel.departement')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_bureau', to='referentiel.region')),
                ('vague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_bureau', to='dossiers.vagueenvoi')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_bureau', to='referentiel.zone')),
            ],
            options={
                'db_table': 'rapport_bureau',
                'ordering': ['-date', '-cree_le'],
            },
        ),
    ]
