# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SIFOR", "SIFOR"), ("DIGIFOR", "DIGIFOR")],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SUCCES", "Succès"),
                            ("ECHEC", "Échec"),
                            ("EN_COURS", "En cours"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lance_le", models.DateTimeField(auto_now_add=True)),
                ("termine_le", models.DateTimeField(blank=True, null=True)),
                ("nb_records", models.IntegerField(default=0)),
                ("message_erreur", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sync_api",
                "ordering": ["-lance_le"],
            },
        ),
        migrations.CreateModel(
            name="FaitAgrege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.CharField(help_text="Format YYYY-MM", max_length=7)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TERRAIN", "Terrain"),
                            ("SIFOR", "SIFOR"),
                            ("DIGIFOR", "DIGIFOR"),
                        ],
                        default="TERRAIN",
                        max_length=10,
                    ),
                ),
                ("nb_dossiers", models.IntegerField(default=0)),
                ("nb_contrats", models.IntegerField(default=0)),
                ("nb_cf", models.IntegerField(default=0)),
                ("nb_anomalies", models.IntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faits",
                        to="referentiel.village",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faits",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "fait_agrege",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("village", "zone", "periode", "source"),
                        name="uix_fait_agrege",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ObjectifPeriode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.CharField(help_text="Format YYYY-MM", max_length=7)),
                ("nb_dossiers", models.IntegerField(default=0)),
                ("nb_contrats", models.IntegerField(default=0)),
                ("nb_cf", models.IntegerField(default=0)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "objectif_periode",
                "unique_together": {("zone", "periode")},
            },
        ),
    ]
