# Generated by Django 6.0.6 on 2026-08-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="profil",
            field=models.CharField(
                choices=[
                    ("CET", "Chef d'Équipe Technique"),
                    ("AGENT_GNSS", "Agent GNSS"),
                    ("CE", "Commissaire-Enquêteur"),
                    ("CR", "Coordonnateur Régional"),
                    ("SIFOR_JUNIOR", "SIFOR Junior"),
                    ("SIFOR_SENIOR", "SIFOR Senior"),
                    ("RAF", "Responsable Administratif et Financier"),
                    ("CHEF_PROJET", "Chef de Projet"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
    ]
