# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportPeriodique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.CharField(help_text="Format YYYY-MM", max_length=7)),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("MENSUEL", "Mensuel"),
                            ("TRIMESTRIEL", "Trimestriel"),
                            ("ANNUEL", "Annuel"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("FINALISE", "Finalisé"),
                            ("ENVOYE", "Envoyé"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="rapports/"),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "redige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapports_rediges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "rapport_periodique",
                "ordering": ["-cree_le"],
                "unique_together": {("zone", "periode", "type_rapport")},
            },
        ),
    ]
