# Generated by Django 6.0.6 on 2026-06-20 18:58

import apps.fichiers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichierDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("PLAN", "Plan"),
                            ("PV", "Procès-verbal"),
                            ("PHOTO", "Photo"),
                            ("DOCUMENT", "Document"),
                            ("RAPPORT", "Rapport"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to=apps.fichiers.models.upload_to)),
                ("taille", models.PositiveIntegerField(blank=True, null=True)),
                ("televerse_le", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichiers",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "televerse_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichiers_televerses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fichier_dossier",
                "ordering": ["-televerse_le"],
            },
        ),
    ]
