# Generated by Django 6.0.6 on 2026-07-18 17:51

import apps.fichiers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichiers", "0001_initial"),
        ("referentiel", "0004_dtv_separation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichierExcelPublicite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "fichier",
                    models.FileField(upload_to=apps.fichiers.models.upload_excel_to),
                ),
                ("taille", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("televerse_le", models.DateTimeField(auto_now_add=True)),
                (
                    "televerse_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excels_televerses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excels_publicite",
                        to="referentiel.village",
                    ),
                ),
            ],
            options={
                "db_table": "fichier_excel_publicite",
                "ordering": ["-televerse_le"],
            },
        ),
    ]
