# Generated by Django 6.0.6 on 2026-09-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0007_dossier_nom_ce_dossier_numero_parcelle_and_more"),
        ("fichiers", "0002_excel_publicite"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="erreurs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="nb_crees",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="nb_maj",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="nb_parcelles",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="superficie_totale",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichierexcelpublicite",
            name="vague_envoi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excels_publicite",
                to="dossiers.vagueenvoi",
            ),
        ),
    ]
