# Generated by Django 6.1 on 2026-08-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_dossier_nom_ce_dossier_observation'),
        ('fichiers', '0002_excel_publicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='erreurs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='nb_crees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='nb_maj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='nb_parcelles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='superficie_totale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fichierexcelpublicite',
            name='vague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers_excel', to='dossiers.vagueenvoi'),
        ),
    ]
