# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TECHNIQUE", "Zone technique"),
                            ("REGIONALE", "Zone régionale"),
                        ],
                        default="TECHNIQUE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "zone",
            },
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="departements",
                        to="referentiel.region",
                    ),
                ),
            ],
            options={
                "db_table": "departement",
                "unique_together": {("nom", "region")},
            },
        ),
        migrations.CreateModel(
            name="SousPrefecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sous_prefectures",
                        to="referentiel.departement",
                    ),
                ),
            ],
            options={
                "db_table": "sous_prefecture",
                "unique_together": {("nom", "departement")},
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("sous_prefecture", models.CharField(max_length=150)),
                ("recueil_historique_fait", models.BooleanField(default=False)),
                ("layons_identifies", models.IntegerField(default=0)),
                ("pv_constat_signes", models.IntegerField(default=0)),
                ("delimite", models.BooleanField(default=False)),
                ("publicite_ouverte", models.BooleanField(default=False)),
                ("publicite_cloturee", models.BooleanField(default=False)),
                ("approuve", models.BooleanField(default=False)),
                ("valide", models.BooleanField(default=False)),
                (
                    "sous_prefecture_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="villages",
                        to="referentiel.sousprefecture",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="villages",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "village",
                "unique_together": {("nom", "sous_prefecture", "zone")},
            },
        ),
    ]
