# Generated by Django 6.0.6 on 2026-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="village",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        # AlterField sous_prefecture_fk retiré : la colonne DB s'appelle déjà
        # sous_prefecture_id (défini via db_column dans le modèle). Django
        # voulait la renommer mais la colonne n'existe pas sous l'ancien nom.
    ]
