# Generated by Django 5.0.1 on 2026-07-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentiel", "0002_village_latitude_village_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="boucle",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="village",
            name="cd_sp_vil",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="village",
            name="clas_preci",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="village",
            name="nom_ota",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="village",
            name="perimetre",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="village",
            name="point_ratt",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="village",
            name="prec_gnss",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="village",
            name="superficie",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="village",
            name="sous_prefecture_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="sous_prefecture_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="villages",
                to="referentiel.sousprefecture",
            ),
        ),
        migrations.CreateModel(
            name="SommetVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("LEVE", "Relevé terrain"),
                            ("PROV", "Provisoire"),
                            ("VALIDE", "Validé"),
                        ],
                        default="LEVE",
                        max_length=10,
                    ),
                ),
                ("num_sommet", models.CharField(blank=True, max_length=20)),
                (
                    "typ_sommet",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BORNE", "Borne"),
                            ("PIQUET", "Piquet"),
                            ("ARBRE", "Arbre"),
                            ("ROCHER", "Rocher"),
                            ("COURS_EAU", "Cours d'eau"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("typ_leve", models.CharField(blank=True, max_length=30)),
                ("coord_x", models.FloatField()),
                ("coord_y", models.FloatField()),
                ("prec_gnss", models.FloatField(blank=True, null=True)),
                ("clas_preci", models.CharField(blank=True, max_length=10)),
                ("amorce", models.BooleanField(default=False)),
                ("nom_agent", models.CharField(blank=True, max_length=100)),
                ("nom_vois", models.CharField(blank=True, max_length=150)),
                ("typ_vois", models.CharField(blank=True, max_length=50)),
                ("typ_nat", models.CharField(blank=True, max_length=50)),
                ("num_tronc", models.CharField(blank=True, max_length=20)),
                ("boucle", models.CharField(blank=True, max_length=50)),
                ("cd_sp_vil", models.CharField(blank=True, max_length=50)),
                ("point_ratt", models.CharField(blank=True, max_length=100)),
                ("date_crea", models.DateField(blank=True, null=True)),
                ("date_maj", models.DateField(blank=True, null=True)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sommets",
                        to="referentiel.village",
                    ),
                ),
            ],
            options={
                "db_table": "sommet_village",
                "ordering": ["village", "num_sommet"],
            },
        ),
    ]
