# Generated by Django 6.1 on 2026-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_dtv_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sousprefecture',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code', 'region'), name='uniq_departement_code_region'),
        ),
        migrations.AddConstraint(
            model_name='sousprefecture',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code', 'departement'), name='uniq_sousprefecture_code_departement'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code', 'sous_prefecture_fk'), name='uniq_village_code_sousprefecture'),
        ),
    ]
