# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        ("referentiel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiviteISF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_activite",
                    models.CharField(
                        choices=[("ISF", "ISF"), ("AUTRE", "Autre")],
                        default="ISF",
                        max_length=20,
                    ),
                ),
                ("date_activite", models.DateField()),
                ("observations", models.TextField(blank=True)),
                ("valide", models.BooleanField(default=False)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites_isf",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "realise_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_isf_realisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activite_isf",
                "ordering": ["-date_activite"],
            },
        ),
        migrations.CreateModel(
            name="FormulairesTerrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_formulaire",
                    models.CharField(
                        choices=[
                            ("LEVE", "Levé"),
                            ("ENQUETE", "Enquête"),
                            ("CONTRAT", "Contrat"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("soumis_le", models.DateTimeField(auto_now_add=True)),
                ("synchro", models.BooleanField(default=False)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulaires",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "soumis_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formulaires_soumis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "formulaire_terrain",
                "ordering": ["-soumis_le"],
            },
        ),
        migrations.CreateModel(
            name="PlanningASFJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_activite", models.DateField()),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                (
                    "type_activite",
                    models.CharField(
                        choices=[
                            ("LEVE", "Levé GNSS"),
                            ("ENQUETE", "Enquête foncière"),
                            ("CONTRAT", "Rédaction contrat"),
                            ("REUNION", "Réunion"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lieu", models.CharField(blank=True, max_length=255)),
                ("observations", models.TextField(blank=True)),
                (
                    "asf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plannings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="plannings",
                        to="referentiel.village",
                    ),
                ),
            ],
            options={
                "db_table": "planning_asf_journalier",
                "ordering": ["date_activite", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Layon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layons",
                        to="referentiel.village",
                    ),
                ),
            ],
            options={
                "db_table": "layon",
                "unique_together": {("village", "identifiant")},
            },
        ),
    ]
