# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleQualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_controle", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "controleur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "controle_qualite",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="AnomalieControle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("BLOQUANTE", "Bloquante"),
                            ("MAJEURE", "Majeure"),
                            ("MINEURE", "Mineure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("corrigee", models.BooleanField(default=False)),
                ("date_correction", models.DateTimeField(blank=True, null=True)),
                (
                    "controle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="controle.controlequalite",
                    ),
                ),
            ],
            options={
                "db_table": "anomalie_controle",
            },
        ),
        migrations.CreateModel(
            name="EnvoiEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plateforme",
                    models.CharField(
                        choices=[
                            ("SCCARTO", "SCCARTO"),
                            ("DIGIFOR", "DIGIFOR"),
                            ("SIFOR", "SIFOR"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYE", "Envoyé"),
                            ("CONFIRME", "Confirmé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("envoye_le", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("observations", models.TextField(blank=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envois",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envois_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "envoi_entreprise",
            },
        ),
    ]
