# Generated by Django 6.0.6 on 2026-08-10 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0004_alter_dossier_statut_cf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueMigrationCouche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_demand", models.CharField(db_index=True, max_length=50)),
                ("ancien_statut", models.CharField(max_length=20)),
                ("nouveau_statut", models.CharField(max_length=20)),
                ("couche_source", models.CharField(blank=True, max_length=150)),
                ("couche_cible", models.CharField(blank=True, max_length=150)),
                ("date_migration", models.DateTimeField(auto_now_add=True)),
                ("succes", models.BooleanField(default=False)),
                ("message_erreur", models.TextField(blank=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migrations_couche",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migrations_couche_effectuees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "historique_migration_couche",
                "ordering": ["-date_migration"],
            },
        ),
    ]
