# Generated by Django 6.0.6 on 2026-06-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_dossier",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "type_dossier",
                    models.CharField(
                        choices=[
                            ("DTV", "Délimitation territoriale de village"),
                            ("CF", "Certification foncière"),
                            ("CONTRACTUALISATION", "Contractualisation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                            ("ARCHIVE", "Archivé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dossiers",
                        to="referentiel.village",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dossiers",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "dossier",
            },
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SIGNE", "Signé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "asf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_rediges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "contrat",
            },
        ),
        migrations.CreateModel(
            name="CertificationFonciere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_cf",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date_delivrance", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("DELIVREE", "Délivrée"),
                            ("SUSPENDUE", "Suspendue"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "certification_fonciere",
            },
        ),
        migrations.CreateModel(
            name="EnqueteFonciere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("TERMINE", "Terminé")],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquete",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "enquete_fonciere",
            },
        ),
        migrations.CreateModel(
            name="HistoriqueStatutDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ancien_statut", models.CharField(max_length=20)),
                ("nouveau_statut", models.CharField(max_length=20)),
                ("modifie_le", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifications_statut",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "historique_statut_dossier",
                "ordering": ["-modifie_le"],
            },
        ),
    ]
