# Generated by Django 5.0.1 on 2026-07-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="boucle",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cd_sp_vil",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dossier",
            name="clas_preci",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="dossier",
            name="n_demcge",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dossier",
            name="nom_demandeur",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="dossier",
            name="nom_ota",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dossier",
            name="num_demand",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dossier",
            name="ocs",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dossier",
            name="perimetre_parcelle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="point_ratt",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dossier",
            name="statut_cf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEVE", "Relevé terrain"),
                    ("PROV", "Provisoire"),
                    ("EN_PUBLICITE", "En publicité"),
                    ("APRES_PUBLICITE", "Après publicité"),
                    ("DEF", "Définitif"),
                    ("REJETE", "Rejeté"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="superficie_parcelle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="type_dossier",
            field=models.CharField(
                choices=[
                    ("DTV", "Délimitation territoire villageois"),
                    ("CF", "Certificat foncier rural"),
                    ("CONTRACTUALISATION", "Contractualisation"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SommetParcelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("LEVE", "Relevé terrain"), ("PROV", "Provisoire")],
                        default="LEVE",
                        max_length=10,
                    ),
                ),
                ("num_sommet", models.CharField(blank=True, max_length=20)),
                ("typ_sommet", models.CharField(blank=True, max_length=30)),
                ("typ_leve", models.CharField(blank=True, max_length=30)),
                ("coord_x", models.FloatField()),
                ("coord_y", models.FloatField()),
                ("prec_gnss", models.FloatField(blank=True, null=True)),
                ("clas_preci", models.CharField(blank=True, max_length=10)),
                ("amorce", models.BooleanField(default=False)),
                ("nom_agent", models.CharField(blank=True, max_length=100)),
                ("nom_vois", models.CharField(blank=True, max_length=150)),
                ("typ_vois", models.CharField(blank=True, max_length=50)),
                ("typ_nat", models.CharField(blank=True, max_length=50)),
                ("num_tronc", models.CharField(blank=True, max_length=20)),
                ("boucle", models.CharField(blank=True, max_length=50)),
                ("cd_sp_vil", models.CharField(blank=True, max_length=50)),
                ("point_ratt", models.CharField(blank=True, max_length=100)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("date_crea", models.DateField(blank=True, null=True)),
                ("date_maj", models.DateField(blank=True, null=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sommets",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "sommet_parcelle",
                "ordering": ["dossier", "num_sommet"],
            },
        ),
    ]
