# Generated by Django 5.0.1 on 2026-07-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dossiers",
            "0002_dossier_boucle_dossier_cd_sp_vil_dossier_clas_preci_and_more",
        ),
        (
            "referentiel",
            "0004_dtv_separation",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VagueEnvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("libelle", models.TextField(blank=True)),
                (
                    "type_dossier",
                    models.CharField(
                        choices=[
                            ("CF", "Certificat Foncier Rural"),
                            ("DTV", "Délimitation Territoire Villageois"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vagues_envoi",
                        to="referentiel.zone",
                    ),
                ),
            ],
            options={
                "db_table": "vague_envoi",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="vague_envoi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dossiers",
                to="dossiers.vagueenvoi",
            ),
        ),
    ]
