# Generated by Django 6.0.6 on 2026-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0003_vagueenvoi_dossier_vague_envoi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="statut_cf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEVE", "Relevé terrain"),
                    ("PROV", "Provisoire"),
                    ("EN_PUBLICITE", "En publicité"),
                    ("APRES_PUBLICITE", "Après publicité"),
                    ("DEF", "Définitif"),
                    ("APPROUVE", "Approuvée"),
                    ("VALIDE", "Validée"),
                    ("REJETE", "Rejeté"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
