# Generated by Django 6.1 on 2026-08-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_refresh_statut_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='nom_ce',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dossier',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
