# Generated by Django 6.0.6 on 2026-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0006_refresh_statut_check_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="nom_ce",
            field=models.CharField(blank=True, max_length=150),
        ),
        # 'numero_parcelle' existe déjà physiquement en base (colonne orpheline héritée d'un
        # ancien schéma, cf. incident dbguard/apps/dossiers/migrations/0005 — column
        # character varying, nullable, compatible avec le champ modèle ci-dessous). On ne fait
        # donc évoluer que l'état Django (pour que le modèle et les migrations futures la
        # connaissent), sans ré-émettre de ADD COLUMN qui échouerait en DuplicateColumn.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="dossier",
                    name="numero_parcelle",
                    field=models.CharField(blank=True, max_length=50),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="dossier",
            name="observation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="statut_publicite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN_PUBLICITE", "En publicité"),
                    ("APPROUVE", "Approuvée"),
                    ("REJETE", "Rejetée"),
                    ("VALIDE", "Validée"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
