# Generated by Django 6.1 on 2026-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_dossier_nom_ce_dossier_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='numero_parcelle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
