# Generated by Django 6.1 on 2026-08-16 16:11

from django.db import migrations, models

# statut_publicite est un nouveau champ distinct de statut_cf (cf. modèle) : les dossiers
# déjà entrés dans le workflow de publicité avant l'ajout de ce champ doivent être backfillés
# pour que les onglets En publicité/Approuvées/Rejetées/Validées restent corrects sans
# repasser par une transition.
STATUTS_PUBLICITE = ('EN_PUBLICITE', 'APPROUVE', 'REJETE', 'VALIDE')


def backfill_statut_publicite(apps, schema_editor):
    Dossier = apps.get_model('dossiers', 'Dossier')
    Dossier.objects.filter(statut_cf__in=STATUTS_PUBLICITE).update(
        statut_publicite=models.F('statut_cf')
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_dossier_numero_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='statut_publicite',
            field=models.CharField(blank=True, choices=[('EN_PUBLICITE', 'En publicité'), ('APPROUVE', 'Approuvée'), ('REJETE', 'Rejetée'), ('VALIDE', 'Validée')], max_length=20, null=True),
        ),
        migrations.RunPython(backfill_statut_publicite, noop_reverse),
    ]
